# These defaults are interpreted by Hydra (a configuration framework) to refer to
# sub-configurations in subfolders of the config folder.
defaults:
  - field: mlp
  - dataset: nerf
  - _self_

nerf:
  num_samples: 128

num_iterations: 8192
visualization_interval: 128
learning_rate: 1e-3
batch_size: 512

output_path: outputs
